/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! The `standard` plugin: the generic Redfish floor.
//!
//! It matches every BMC with [`MatchSpecificity::Generic`] and implements the
//! capabilities that are universally standard (power read/set and manager
//! reset/status). Vendor-specific capabilities are intentionally left
//! unimplemented (`None`), so the runtime surfaces `NotSupported` for them --
//! exactly the behavior `RedfishStandard` has in `libredfish` today. Vendor
//! plugins (including ones generated by the plugin-generation skill) fill in
//! the specifics.

use async_trait::async_trait;
use carbide_redfish_platform_api::RedfishError;
use carbide_redfish_platform_api::model::{
    BmcResetKind, BmcStatus, ChassisResetRequest, MatchSpecificity, PlatformIdentity,
    PlatformMetadata, PluginId, PowerAction, PowerState, SupportLevel,
};
use carbide_redfish_platform_api::ops::PlatformExecutionContext;
use carbide_redfish_platform_api::plugin::{BmcResetCap, HostPowerCap, PlatformPlugin};

use crate::providers;

/// The standard generic Redfish plugin.
pub struct StandardPlugin {
    metadata: PlatformMetadata,
    power: StandardPowerCap,
    bmc_reset: StandardBmcResetCap,
}

impl StandardPlugin {
    /// Construct the standard plugin.
    pub fn new() -> Self {
        Self {
            metadata: PlatformMetadata {
                id: PluginId("nico.redfish.standard".to_string()),
                vendor: "Standard",
                models: &["*"],
                plugin_version: env!("CARGO_PKG_VERSION"),
                support_level: SupportLevel::CoreMaintained,
            },
            power: StandardPowerCap,
            bmc_reset: StandardBmcResetCap,
        }
    }
}

impl Default for StandardPlugin {
    fn default() -> Self {
        Self::new()
    }
}

impl PlatformPlugin for StandardPlugin {
    fn metadata(&self) -> &PlatformMetadata {
        &self.metadata
    }

    fn detect(&self, _identity: &PlatformIdentity) -> Option<MatchSpecificity> {
        // The generic floor: matches everything, least specific.
        Some(MatchSpecificity::Generic)
    }

    fn power(&self) -> Option<&dyn HostPowerCap> {
        Some(&self.power)
    }

    fn bmc_reset(&self) -> Option<&dyn BmcResetCap> {
        Some(&self.bmc_reset)
    }
}

/// Standard host power via `ComputerSystem.Reset`.
pub struct StandardPowerCap;

#[async_trait]
impl HostPowerCap for StandardPowerCap {
    async fn power_state(
        &self,
        ctx: &PlatformExecutionContext<'_>,
    ) -> Result<PowerState, RedfishError> {
        providers::standard_power_state(ctx).await
    }

    async fn set_power(
        &self,
        ctx: &PlatformExecutionContext<'_>,
        action: PowerAction,
    ) -> Result<(), RedfishError> {
        let reset_type = providers::reset_type(action).ok_or_else(|| {
            RedfishError::not_supported("AC power cycle is not supported by the standard provider")
        })?;
        providers::standard_set_power(ctx, reset_type).await
    }
}

/// Standard BMC reset via `Manager.Reset`.
pub struct StandardBmcResetCap;

#[async_trait]
impl BmcResetCap for StandardBmcResetCap {
    async fn bmc_status(
        &self,
        ctx: &PlatformExecutionContext<'_>,
    ) -> Result<BmcStatus, RedfishError> {
        let (firmware_version, date_time) = providers::standard_manager_status(ctx).await?;
        Ok(BmcStatus {
            ready: true,
            firmware_version,
            date_time,
        })
    }

    async fn reset_bmc(
        &self,
        ctx: &PlatformExecutionContext<'_>,
        kind: BmcResetKind,
    ) -> Result<(), RedfishError> {
        let reset_type = match kind {
            BmcResetKind::GracefulRestart => "GracefulRestart",
            BmcResetKind::ForceRestart => "ForceRestart",
            BmcResetKind::ResetToDefaults => {
                return Err(RedfishError::not_supported(
                    "Manager ResetToDefaults is not supported by the standard provider",
                ));
            }
        };
        providers::standard_reset_bmc(ctx, reset_type).await
    }

    async fn reset_chassis(
        &self,
        ctx: &PlatformExecutionContext<'_>,
        req: ChassisResetRequest,
    ) -> Result<(), RedfishError> {
        let reset_type = match req.kind {
            BmcResetKind::GracefulRestart => "GracefulRestart",
            BmcResetKind::ForceRestart => "ForceRestart",
            BmcResetKind::ResetToDefaults => {
                return Err(RedfishError::not_supported(
                    "ResetToDefaults is not a chassis reset",
                ));
            }
        };
        providers::standard_chassis_reset(ctx, &req.chassis_id, reset_type).await
    }

    async fn set_bmc_time_utc(
        &self,
        ctx: &PlatformExecutionContext<'_>,
    ) -> Result<(), RedfishError> {
        providers::standard_set_bmc_time_utc(ctx).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use carbide_redfish_platform_api::plugin::PlatformPlugin;

    #[test]
    fn standard_matches_everything_as_generic_floor() {
        let plugin = StandardPlugin::new();
        let detected = plugin.detect(&PlatformIdentity::default());
        assert_eq!(detected, Some(MatchSpecificity::Generic));
    }

    #[test]
    fn standard_implements_power_and_bmc_reset_only() {
        let plugin = StandardPlugin::new();
        assert!(plugin.power().is_some());
        assert!(plugin.bmc_reset().is_some());
        // Vendor-specific capabilities are the generic floor's NotSupported.
        assert!(plugin.machine_setup().is_none());
        assert!(plugin.boot_order().is_none());
        assert!(plugin.firmware().is_none());
        assert!(plugin.storage().is_none());
    }
}
